import pandas as pd
df = pd.read_csv(r"/Users/ashishgoni/Downloads/Titanic.csv")
print(df.head())
print(df.tail())
print(df.shape)
print(df.columns)
print(df.dtypes)
df.info()
print(df.describe())
print(df["Age"].mean())
print(df["Age"].median())
print(df["Age"].mode()[0])
print(df["Age"].var())
print(df["Age"].std())
print(df["Age"].min())
print(df["Age"].max())
print(df["Age"].count())
print(df["Embarked"].unique())
print(df["Embarked"].nunique())
print(df["Embarked"].value_counts())
print(df.isnull().sum())
print(df.isnull().mean() * 100)
df_clean = df.dropna()
df_filled = df.fillna(0)
print(df.duplicated().sum())
df_no_dups = df.drop_duplicates()
print(df["Age"])
print(df[["Age", "Fare"]])
print(df.iloc[0:5])
print(df[df["Age"] > 30])
print(df.sort_values("Age"))
df = df.rename(columns={"Age": "Age_Years"})
df["Fare_Tax"] = df["Fare"] * 0.10
df = df.drop("Fare_Tax", axis=1)
print(df.groupby("Pclass")["Fare"].mean())
df1 = df.iloc[:5]
df2 = df.iloc[5:10]
combined = pd.concat([df1, df2])
merged = pd.merge(df1, df2, on="PassengerId", how="outer")
print(combined)
print(merged)